services:
  spark-notebook:
    build: .
    container_name: spark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python